### ISSUE TITLE
请问如何更改网站的logo

### ISSUE THREAD

**Issue by desti-nation** [mzlogin/mzlogin.github.io#76]

**Comment by mzlogin** [comment]
在 <https://mazhuang.org/about/> 页面的评论里可以看到方法，摘录如下：

## 更换首页左上角图标

可以修改 _includes/header.html 第 76 行：

```html
<h1><a href="{{ site.url }}/" title="{{ site.title }}"><span class="octicon octicon-mark-github"></span> {{ site.title }}</a></h1>
```

预览图网址：

https://octicons.github.com/

对应的图片代号可以在 assets/vendor/octicons/octicons/octicons.css 搜到，如camera，

可直接搜索camera，对应代号为：

```css
.octicon-device-camera:before { content: '\f056'} /*  */
```

## 更换网站地址栏小图标

换掉 favicon.ico 文件即可。
